name: Build cv_KelliJohnson.tex
on:
  workflow_call:
    inputs:
      ref:
        default: ${{ github.ref }}
        required: false
        type: string
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2
        with: 
          ref: ${{ inputs.ref }}
        
      - name: remove rendered file, check that is gone.
        run: |
          rm -rf cv_KelliJohnson.pdf
          ls
     # - name: add lua filter to the repository
     #  run: wget https://raw.githubusercontent.com/klpn/accpdf/master/common/tagged-filter.lua      
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_KelliJohnson.tex
          #args: --lua-filter=tagged-filter.lua
          latexmk_use_lualatex: trues
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v2
        with:
          name: cv_KelliJohnson.pdf
          path: cv_KelliJohnson.pdf
          
      - name: Upload log file when job fails
        if: failure()
        uses: actions/upload-artifact@v2
        with: 
          name: cv_KelliJohnson.log
          path: cv_KelliJohnson.log
